import localFont from "next/font/local";
import "./globals.css";
import { getDocuments } from "@/lib/doc";
import Navbar from "@/Components/Header/Navbar";
import Sidebar from "@/Components/Header/Sidebar";
import Footer from "@/Components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const allDocuments = getDocuments();
  console.log(allDocuments);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <div className="flex min-h-screen">
          {/* sidebar */}
          <aside className="w-1/5 bg-red-100">
<Sidebar/>
          </aside>

          <main className="w-4/5 p-5 bg-white">
          
        {children}
          </main>
        </div>
        {/* footer */}
        <Footer/>
      </body>
    </html>
  );
}
